<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Functional Suite" duration-ms="10651" started-at="2017-12-03T07:26:08Z" finished-at="2017-12-03T07:26:19Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="10651" started-at="2017-12-03T07:26:08Z" finished-at="2017-12-03T07:26:19Z">
      <class name="testcases.BankManagerLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.BankManagerLoginTest@4f67eb2a]" name="setUp" is-config="true" duration-ms="12708" started-at="2017-12-03T12:55:56Z" finished-at="2017-12-03T12:56:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:testcases.BankManagerLoginTest@4f67eb2a]" name="loginAsBankManager" duration-ms="10601" started-at="2017-12-03T12:56:08Z" finished-at="2017-12-03T12:56:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add customer button not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add customer button not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.BankManagerLoginTest@4f67eb2a]" name="tearDown" is-config="true" duration-ms="1087" started-at="2017-12-03T12:56:19Z" finished-at="2017-12-03T12:56:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
